### ISSUE TITLE
Provide environment.yml for easy installation using conda

### ISSUE THREAD

**Issue by fritzo** [jrg365/gpytorch#39]
It looks like conda-forge provides libfftw3: https://anaconda.org/conda-forge/fftw

I haven't tried this, but maybe you could ease the installation process with an `environment.yml` like
```
name: gpytorch
channels:
  - conda-forge
dependencies:
  - cffi
  - fftw
```
and then simply
```sh
conda env create -f environment.yml
source activate gpytorch
pip install .
```
(sorry, I'm not a conda expert)

**Comment by jrg365** [comment]
This is an interesting thought, I didn't realize conda provides fftw. I'll try this out and if it works I would probably be in favor of using this as the installation process. @gpleiss?

**Comment by jrg365** [comment]
Unless I am mistaken, this has been resolved -- the installation instructions now recommend at a minimum installing fftw through conda, and we now provide environment files for both CUDA and CPU versions of GPyTorch.
